# - Find cpppcms
# Find the cppcms includes and library and the booster include and library
#
#  CPPCMS_INCLUDE_DIR - Where to find cppcms include sub-directory.
#  CPPCMS_LIBRARIES   - List of libraries when using CPPCMS.
#  CPPCMS_FOUND       - True if CPPCMS found.
#  BOOSTER_INCLUDE_DIR - Where to find booster include sub-directory.
#  BOOSTER_LIBRARIES   - List of libraries when using BOOSTER.
#  BOOSTER_FOUND       - True if BOOSTER found.


IF (CPPCMS_INCLUDE_DIR)
	# Already in cache, be silent.
	SET(CPPCMS_FIND_QUIETLY TRUE)
ENDIF (CPPCMS_INCLUDE_DIR)

FIND_PATH(CPPCMS_INCLUDE_DIR cppcms)
FIND_PATH(BOOSTER_INCLUDE_DIR booster)

FIND_LIBRARY(CPPCMS_LIBRARY NAMES cppcms)
FIND_LIBRARY(BOOSTER_LIBRARY NAMES booster)


# Handle the QUIETLY and REQUIRED arguments and set CPPCMS_FOUND to
# TRUE if all listed variables are TRUE.
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	CPPCMS DEFAULT_MSG
	CPPCMS_LIBRARY CPPCMS_INCLUDE_DIR
)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
	BOOSTER DEFAULT_MSG
	BOOSTER_LIBRARY BOOSTER_INCLUDE_DIR
)

IF(CPPCMS_FOUND)
	SET( CPPCMS_LIBRARIES ${CPPCMS_LIBRARY} ${BOOSTER_LIBRARY})
ELSE(CPPCMS_FOUND)
	SET(CPPCMS_LIBRARIES )
ENDIF(CPPCMS_FOUND)

MARK_AS_ADVANCED( CPPCMS_LIBRARY CPPCMS_INCLUDE_DIR BOOSTER_LIBRARY BOOSTER_INCLUDE_DIR )